# Generated by Django 3.0.5 on 2020-06-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bss_set1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_non_current_asset', models.DecimalField(decimal_places=3, max_digits=15)),
                ('total_current_asset', models.DecimalField(decimal_places=3, max_digits=15)),
                ('inventories', models.DecimalField(decimal_places=3, max_digits=15)),
                ('trade_other_current', models.DecimalField(decimal_places=3, max_digits=15)),
                ('cash', models.DecimalField(decimal_places=3, max_digits=15)),
                ('issued_capital', models.DecimalField(decimal_places=3, max_digits=15)),
                ('eqity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('non_current_liability', models.DecimalField(decimal_places=3, max_digits=15)),
                ('current_liability', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('period1', models.IntegerField()),
                ('period2', models.IntegerField()),
            ],
        ),
    ]
